/* NAME:
 * create_table_CONSTRAINTS.sql
 *
 * DESC:
 * script used to create various constraints on previously created tables to primarily ensure data integrity
 * 
 * LOG:
 * VERSION---DATE--------NAME-------------COMMENT
 * 0.1       04SEP2014   Johan Louwers    Initial upload to github.com
 * 0.2       05SEP2014   Johan Louwers    added constraints for T_OOPIMS_MANUFACT table
 * 0.3       05SEP2014   Johan Louwers    corrected comments.
 *
 * LICENSE:
 * Copyright (C) 2014  Johan Louwers
 * 
 * This code is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This code is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this code; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * 
 */
 
ALTER TABLE T_OOPIMS_ACCOUNTS ADD CONSTRAINT T_OOPIMS_ACCOUNTS_PK PRIMARY KEY ( ID ) ;

ALTER TABLE T_OOPIMS_CATALOG ADD CONSTRAINT T_OOPIMS_CATALOG_PK PRIMARY KEY ( ID ) ;

ALTER TABLE T_OOPIMS_PRODUCTDETAILS ADD CONSTRAINT T_OOPIMS_PRODUCTDETAILS_PK PRIMARY KEY ( ID ) ;

ALTER TABLE T_OOPIMS_PRODUCTS ADD CONSTRAINT T_OOPIMS_PRODUCTS_PK PRIMARY KEY ( ID ) ;

ALTER TABLE T_OOPMIS_CATITEMS ADD CONSTRAINT T_OOPMIS_CATITEMS_PK PRIMARY KEY ( ID ) ; 

ALTER TABLE T_STATIC_STATUS ADD CONSTRAINT T_STATIC_STATUS_PK PRIMARY KEY ( ID ) ;

ALTER TABLE T_OOPIMS_MANUFACT ADD CONSTRAINT T_OOPIMS_MANUFACT_PK PRIMARY KEY ( ID ) ;

ALTER TABLE T_OOPIMS_ACCOUNTS ADD CONSTRAINT T_OOPIMS_ACCOUNTS_ACC_STATUS FOREIGN KEY ( ACC_STATUS ) REFERENCES T_STATIC_STATUS ( ID ) ;

ALTER TABLE T_OOPIMS_CATALOG ADD CONSTRAINT T_OOPIMS_CATALOG_CREATED_BY FOREIGN KEY ( CREATED_BY ) REFERENCES T_OOPIMS_ACCOUNTS ( ID ) ;

ALTER TABLE T_OOPIMS_CATALOG ADD CONSTRAINT T_OOPIMS_CATALOG_STATUS FOREIGN KEY ( CATALOG_STATUS ) REFERENCES T_STATIC_STATUS ( ID ) ;

ALTER TABLE T_OOPIMS_CATALOG ADD CONSTRAINT T_OOPIMS_CATALOG_UPDATED_BY FOREIGN KEY ( UPDATED_BY ) REFERENCES T_OOPIMS_ACCOUNTS ( ID ) ;

ALTER TABLE T_OOPIMS_PRODUCTDETAILS ADD CONSTRAINT "T_OOPIMS_PR-DET_CREATED_BY" FOREIGN KEY ( CREATED_BY ) REFERENCES T_OOPIMS_ACCOUNTS ( ID ) ;

ALTER TABLE T_OOPIMS_PRODUCTDETAILS ADD CONSTRAINT "T_OOPIMS_PR-DET_PRODUCT_ID" FOREIGN KEY ( PRODUCT_ID ) REFERENCES T_OOPIMS_PRODUCTS ( ID ) ;

ALTER TABLE T_OOPIMS_PRODUCTDETAILS ADD CONSTRAINT "T_OOPIMS_PR-DET_PRODUCT_STATUS" FOREIGN KEY ( PRODUCT_STATUS ) REFERENCES T_STATIC_STATUS ( ID ) ;

ALTER TABLE T_OOPIMS_PRODUCTDETAILS ADD CONSTRAINT "T_OOPIMS_PR-DET_UPDATED_BY" FOREIGN KEY ( UPDATED_BY ) REFERENCES T_OOPIMS_ACCOUNTS ( ID ) ;

ALTER TABLE T_OOPIMS_PRODUCTS ADD CONSTRAINT T_OOPIMS_PR_CREATED_BY FOREIGN KEY ( CREATED_BY ) REFERENCES T_OOPIMS_ACCOUNTS ( ID ) ;

ALTER TABLE T_OOPIMS_PRODUCTS ADD CONSTRAINT T_OOPIMS_PR_PRODUCT_STATUS FOREIGN KEY ( PRODUCT_STATUS ) REFERENCES T_STATIC_STATUS ( ID ) ;

ALTER TABLE T_OOPIMS_PRODUCTS ADD CONSTRAINT T_OOPIMS_PR_UPDATED_BY FOREIGN KEY ( UPDATED_BY ) REFERENCES T_OOPIMS_ACCOUNTS ( ID ) ;

ALTER TABLE T_OOPMIS_CATITEMS ADD CONSTRAINT T_OOPMIS_CATITEMS_CATALOG FOREIGN KEY ( CATALOG ) REFERENCES T_OOPIMS_CATALOG ( ID ) ;

ALTER TABLE T_OOPMIS_CATITEMS ADD CONSTRAINT T_OOPMIS_CATITEMS_PRODUCT FOREIGN KEY ( PRODUCT ) REFERENCES T_OOPIMS_PRODUCTS ( ID ) ;

ALTER TABLE T_OOPMIS_CATITEMS ADD CONSTRAINT T_OOPMIS_CATITEMS_STATUS FOREIGN KEY ( STATUS ) REFERENCES T_STATIC_STATUS ( ID ) ;

ALTER TABLE T_OOPIMS_MANUFACT ADD CONSTRAINT T_OOPIMS_MANUFACT_STATUS FOREIGN KEY ( MANUFAC_STATUS ) REFERENCES T_STATIC_STATUS ( ID ) ;
